preset: "simple"
releasePrefix: "v"

# Changelog yapılandırması
changelog:
  path: "CHANGELOG.md"
  append: true
  includeLatestRelease: true
  templates:
    default:
      content: |
        # Changelog
        {{#releases}}
        ## {{name}}{{#if date}} ({{date}}){{/if}}
        {{#changes}}
        * {{message}}
        {{/changes}}
        {{/releases}}

# Versiyonlama ayarları
versioning:
  mode: "semver"
  initialVersion: "0.1.0"
  enabled: true

# Sürüm türleri ve yapılandırma
releaseTypes:
  enabled:
    - mainline
  items:
    mainline:
      description: "Mainline releases"
      gitPush: true
      gitTag: true
      matchBranches: "^(master|main)$"
      publish: true
      bump:
        default: "patch"

resume: true
stateFile: ".nyx-state.json"
