preset: simple
releasePrefix: v

# Changelog yapılandırması
changelog:
  path: CHANGELOG.md
  templates:
    default:
      content: "{{#releases}}# {{name}}{{#sections}}\n\n## {{name}}\n\n{{#commits}}* {{#hash}}[{{.}}] {{/hash}}{{message}}{{#author}} ({{.}}){{/author}}\n{{/commits}}{{/sections}}{{/releases}}"
  sections:
    feat: "Features" 
    fix: "Bug Fixes"
    docs: "Documentation"
    refactor: "Code Refactoring"
    test: "Tests"
    build: "Build System"
    ci: "Continuous Integration"

# Commit mesaj yapılandırması
commitMessageConventions:
  enabled:
    - conventionalCommits
  items:
    conventionalCommits:
      expression: "^(?<type>build|ci|docs|feat|fix|perf|refactor|test)(?:\\((?<scope>[^\\)]+)\\))?!?:(\\s|\\s\\n)(?<title>.+)$"
      bumpExpressions:
        feat: "minor"
        fix: "patch"
        breaking: "major"

# Versiyon yapılandırması
versioning:
  enabled: true
  startingVersion: 0.1.0
  mode: semver

initialVersion: 0.1.0

# Sürüm türleri
releaseTypes:
  mainline:
    matchBranches: "^(master|main|develop)$"
    description: "Mainline releases for production"
    collapseVersions: false
    filterTags: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    bump:
      default: patch
  
  feature:
    matchBranches: "^(feature|feat)\\/.*$"
    description: "Feature branch releases"
    collapsed: false
    filterTags: "^v[0-9]+\\.[0-9]+\\.[0-9]+-(alpha|beta)\\.[0-9]+$"
    prefix: alpha
    bump:
      default: prerelease
      
  hotfix:
    matchBranches: "^(hotfix|fix)\\/.*$"
    description: "Hotfix releases"
    collapsed: false
    filterTags: "^v[0-9]+\\.[0-9]+\\.[0-9]+-(rc)\\.[0-9]+$"
    prefix: rc
    bump:
      default: prerelease

# Servis yapılandırması
services:
  github:
    type: github
    options:
      repository: nyx-demo
      authentication: token