preset: 'simple'
releasePrefix: 'v'

changelog:
  path: 'CHANGELOG.md'

commitMessageConventions:
  enabled:
    - 'conventionalCommits'

releaseTypes:
  mainline:
    matchBranches: "^(master|main|develop)$" # 'develop' eklendi