preset: simple
releasePrefix: v

changelog:
  path: CHANGELOG.md
  includeLatestRelease: true
  sections:
    features: "🚀 Features"
    fixes: "🐛 Bug Fixes"
    chores: "🔧 Maintenance"
  templates:
    default:
      content: |
        # Changelog
        {{#releases}}
        ## {{name}}{{#if date}} ({{date}}){{/if}}
        {{#each sections}}
        ### {{title}}
        {{#changes}}
        * {{message}}
        {{/changes}}
        {{/each}}
        {{/releases}}

versioning:
  mode: semver
  initialVersion: 0.1.0
  enabled: true

commitMessageConventions:
  enabled:
    - conventionalCommits
  items:
    conventionalCommits:
      expression: "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([a-z0-9 ,-]+\\))?!?: (.+)$"
      bumpExpressions:
        major: "^(feat|fix|refactor|perf)(\\([a-z0-9 ,-]+\\))?!:"
        minor: "^feat(\\([a-z0-9 ,-]+\\))?:"
        patch: "^(fix|perf)(\\([a-z0-9 ,-]+\\))?:"
      serviceMapping:
        features: "^feat.*$"
        fixes: "^fix.*$"
        chores: "^(chore|refactor|docs|style|test|build|ci|perf|revert).*$"

releaseTypes:
  enabled:
    - mainline
  publicationServices:
    - github
  items:
    mainline:
      description: Mainline releases
      gitPush: true
      gitTag: true
      matchBranches: ^(master|main)$
      publish: true
      bump:
        default: patch

services:
  github:
    type: GITHUB
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      REPOSITORY_OWNER: "YigitEmreTurkkan"
      REPOSITORY_NAME: "nyxdemo"

resume: true
stateFile: .nyx-state.json
